#application: lsh-test-app-tb
application: open-lsh
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /favicon.ico
  static_dir: static/images

- url: /mapreduce/pipeline/images
  static_dir: mapreduce/lib/pipeline/ui/images

- url: /static/js/custom.js
  static_files: static/js/custom.js
  upload: static/js/custom.js

- url: /assets
  static_dir: twitter-bootstrap/assets

#- url: /mapreduce(/.*)?
#  script: libs.mapreduce.main.APP

- url: /coming_soon
  script: main.application

- url: /twitter_.*
  script: main.application

- url: /
  script: main.application

- url: /.*
  script: main.application
  login: admin

env_variables:
 GAE_USE_SOCKETS_HTTPLIB : True

includes:
- mapreduce/include.yaml

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest

builtins:
- deferred: on
